
2016-02-25 14:56:07,431 DEBUG    [sublayers_server.model.agents->agents.py:150 ] Agent <User #139774332642384 AKA u'777'> saved
2016-02-25 14:56:07,431 DEBUG    [sublayers_server.model.agents->agents.py:382 ] <User #139774332642384 AKA u'777'>:: on_enter_location(<Town #139774880259664> => u'\u041f\u
0440\u0430\u0439\u043e\u0440')
2016-02-25 14:56:07,591 INFO     [sublayers_server.model.server_api->server_api.py:47  ] Server API: Old Agent given: 56cee963d7bd900579b48fc6
2016-02-25 14:56:08,742 DEBUG    [sublayers_server.model.agents->agents.py:386 ] <User #139774332835600 AKA u'abbir'>:: on_exit_location(<Town #139774880259664> => u'\u041f\
u0440\u0430\u0439\u043e\u0440')
2016-02-25 14:56:23,588 DEBUG    [sublayers_server.model.agents->agents.py:392 ] <User #139774332642384 AKA u'777'>:: on_enter_npc(<Armorer@reg://registry/institutions/armor
er/timofey>)
2016-02-25 14:56:31,477 DEBUG    [sublayers_server.model.agents->agents.py:386 ] <User #139774332642384 AKA u'777'>:: on_exit_location(<Town #139774880259664> => u'\u041f\u0
440\u0430\u0439\u043e\u0440')
2016-02-25 14:56:45,011 ERROR    [sublayers_server.model.event_machine->event_machine.py:206 ] Event performing error <EnterToMapLocation #139774331856336 [14:56:44.919]>
Traceback (most recent call last):
  File "/home/sl/sublayers/sublayers_server/model/event_machine.py", line 204, in event_loop
    event.perform()
  File "/home/sl/sublayers/sublayers_server/model/events.py", line 94, in perform
    self.on_perform()
  File "/home/sl/sublayers/sublayers_server/model/events.py", line 299, in on_perform
    obj.on_enter(agent=self.agent, time=self.time)
  File "/home/sl/sublayers/sublayers_server/model/map_location.py", line 61, in on_enter
    for building in self.example.buildings.values():
AttributeError: 'GasStation' object has no attribute 'buildings'
2016-02-25 14:56:52,213 ERROR    [sublayers_server.model.event_machine->event_machine.py:206 ] Event performing error <EnterToMapLocation #139774332105040 [14:56:52.157]>
Traceback (most recent call last):
  File "/home/sl/sublayers/sublayers_server/model/event_machine.py", line 204, in event_loop
    event.perform()
  File "/home/sl/sublayers/sublayers_server/model/events.py", line 94, in perform
    self.on_perform()
  File "/home/sl/sublayers/sublayers_server/model/events.py", line 299, in on_perform
    obj.on_enter(agent=self.agent, time=self.time)
  File "/home/sl/sublayers/sublayers_server/model/map_location.py", line 61, in on_enter
    for building in self.example.buildings.values():
AttributeError: 'GasStation' object has no attribute 'buildings'
2016-02-25 14:56:57,903 INFO     [sublayers_server.model.server_api->server_api.py:47  ] Server API: Old Agent given: 56cee874d7bd900579b48fc5
2016-02-25 14:57:03,952 INFO     [sublayers_server.handlers.client_connector->client_connector.py:50  ] Agent socket <sublayers_server.handlers.client_connector.AgentSocketHandler object at 0x7f1fbecf2810> Closed


